### PR TITLE
New record colors

### PR DESCRIPTION
**Pull request by AdriCardenas**
Improve color of the text and background of the mini sectors and the times of a pilot

### CODE REVIEW

**Comment by Slowlydev** [comment]
Thanks for the PR. I think the background color in `LeaderBoard.tsx` is still the old purple, could you also adjust that?

**Comment by AdriCardenas** [comment]
Hi,

> Thanks for the PR. I think the background color in `LeaderBoard.tsx` is still the old purple, could you also adjust that?

I review the `LeaderBoard.tsx` file but i have not found colors on it. Just the `bg-gray-700` on the skeleton.

**Comment by Slowlydev** [comment]
> Hi,
> 
> > Thanks for the PR. I think the background color in `LeaderBoard.tsx` is still the old purple, could you also adjust that?
> 
> I review the `LeaderBoard.tsx` file but i have not found colors on it. Just the `bg-gray-700` on the skeleton.

nevermind, my bad, it should be in the `Driver.tsx`

**Comment by Slowlydev** [comment]
Also maybe violet could match better, because as you said the original color was kind of blueish, and that was because all other ui elements have a slight blue tint.

image

**Comment by AdriCardenas** [comment]
> Also maybe violet could match better, because as you said the original color was kind of blueish, and that was because all other ui elements have a slight blue tint.
> 
> image

Sure, i had that doubt. I'll  change it in a new commit because both of them are good.

**Comment by AdriCardenas** [comment]
What is the meaning of minisector blue color?

`"bg-blue-500": status === 2064`

**Comment by AdriCardenas** [comment]
> What is the meaning of minisector blue color?
> 
> `"bg-blue-500": status === 2064`

Should be on the help tab. I think that it is enter and exit of boxes.

**Comment by Slowlydev** [comment]
> > What is the meaning of minisector blue color?
> 
> > 
> 
> > `"bg-blue-500": status === 2064`
> 
> 
> 
> Should be on the help tab. I think that it is enter and exit of boxes.

Yes thats true.

**Comment by Slowlydev** [comment]
thanks for the adjustments, looks good to me 😄

**Review by Slowlydev — APPROVED** [review]

**Pull request merged**
