### PR TITLE
feature/v2

### PR DESCRIPTION
**Pull request by slowlydev**
This is v2 of f1-dash.

What did change?
- frontend (dashboard)

  - new UI design
  - new landing page
  - new navigation
  - new weather data design
  - warnings when switching away form live timing
  - walkthrough to explain UI elements
  - graphs of gap, lap time and sector history for every driver
  - track limits tracker
  - additional windows for track limits, team radios, race control messages, map
  - schedule of all upcoming races with live countdowns
  - customizable UI (stage 1)

- backend

  - rewrite in rust
  - partial updates to reduce network usage on client and server
  - new separate backend to handle other endpoints like schedule
  - provide history of gap, lap time, sectors and weather data (weather is not used yet)
  - provide updates and initial states all the way back to race start (not implemented in frontend yet)
 
This update fixes/closes:

- #56  (probably, reworked DRS detection and state updates)
- #45 (not perfect yet)
- #57 (hopefully)
- #38
- #81

V2 is not quite ready yet, I still want to do following things:

- [x] Write new help page for changes
- [x] Setting to redo walkthrough
- [x] fix weather icon not showing active
- [x] Qualifying and Practice session numbers not correct
- [x] fix schedule page showing wrong time and countdown failing when directly going to page or reloading on page
- [x] improve mobile UI
~~- [ ] More Steps for Initial Walkthrough~~ (walkthrough delayed fast initial v2)
~~- [ ] Toggle More UI parts~~ (delayed, common with customisable filters after v2 release)
- [ ] Rigorous Testing to make sure it runs well

### CODE REVIEW

**Comment by Aarekaz** [comment]
This looks absolutely awesome @slowlydev . Also seems like I mistakenly pressed request access when viewing this preview. Please ignore/deny that. 

I cant wait to test this fully on the next gp. 

Do let me know if you need any help on Dashboard Designs and copy writing. Would absolutely love to help/test things out.

**Comment by slowlydev** [comment]
Hey there @Aarekaz 

> This looks absolutely awesome @slowlydev . Also seems like I mistakenly pressed request access when viewing this preview. Please ignore/deny that.

Thank you! no worries u can access v2, without preview access on [v2.f1-dash.com](https://v2.f1-dash.com/)

> I cant wait to test this fully on the next gp.

Yeah I hope its working better than the current production version, please don't share it too much, just yet :)

> Do let me know if you need any help on Dashboard Designs and copy writing. Would absolutely love to help/test things out.

Yeah please feel free to test it out, when doing heavy load testing please do it locally, but going on the page and using it and clicking around during a Session is no problem at all.

Help is much appreciated, for example the help page needs a re write, and maybe an "outside" "non main dev" perspective would be good for that, because everything just makes kinda sense to me 😅

I need some designing of the Head-to-Head page (that would not be v2 but come some time after) as I don't quite know what data to show, what would be interesting to compare between drivers and how to visualise this. I would be important of course that it's being checked that we saccutally have access to that data. What I wanna say with this is that one needs to checkout the TypeScript types or the data that formula one sends.

**Comment by Aarekaz** [comment]
No worries, I will test it out in the next GP.

I sent you a discord friend request, let's chat there and let's see how I can help with the design/ general documentation for the website. Absolutely love this.

**Comment by tooboredtocode** [comment]
Hi, you asked me to look through the code and I finally have some time :)
First off, is there any reason you aren't using [cargo workspaces](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html)?

**Comment by slowlydev** [comment]
> Hi, you asked me to look through the code and I finally have some time :) First off, is there any reason you aren't using [cargo workspaces](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html)?

No, no reason. just did not know about it ...

**Comment by tooboredtocode** [comment]
Other than that, I didn't find anything out of the ordinary...

Creating a custom struct to hold state (and mutate it) might speed up performance when reconstructing an inital state (when properly done). Alternatively, you could save a complete copy of the state every X minutes, so at most 5 minutes have to be reconstructed...

**Pull request merged**
